#!/usr/bin/env python3
"""Course JSON (magnetic tape polylines) -> URDF for the Unity simulator.

The simulator's magnetic guide sensor (UnitySensors ``MagneticGuideSensor``,
URDF ``<sensor type="magnetic_guide">``) reads trigger colliders that carry a
``MagneticTape`` component.  This script writes such a course as ONE URDF
entity: a ``world``-fixed link whose ``<collision>`` shapes are thin boxes,
one per polyline segment, tagged through ``<collision_material>``::

    <collision_material name="track">  <magnetic_tape polarity="track"/>  </collision_material>
    <collision_material name="marker"> <magnetic_tape polarity="marker"/> </collision_material>

``magnetic_tape`` implies ``sensor_only`` (the boxes are triggers), so the
robot drives over them and the lidar, which scans above the floor, does not
see them.  Visual boxes are emitted too so the course shows in the GUI.

Course JSON::

    { "tapes": [
        { "kind": "track",  "width": 0.025, "points": [[0,0],[10,0],[12,2]] },
        { "kind": "marker", "width": 0.025, "points": [[5.0,0.035],[5.3,0.035]] } ] }

``kind`` is "track" or "marker"; ``points`` are world (ROS) x,y in metres.
Markers go 15-30 mm outside the track edge (sensor datasheet).  Corners are
plain segment joints; for a smooth arc supply the polyline densely.

Usage:
    gen_tape_urdf.py course.json course.urdf [--thickness 0.001] [--no-visual]
    gen_tape_urdf.py --self-test
"""
import argparse
import json
import math
import os
import sys
import xml.etree.ElementTree as ET

COLOR = {"track": "0.15 0.15 0.15 1", "marker": "0.6 0.1 0.1 1"}


def segments(points):
    for (x0, y0), (x1, y1) in zip(points, points[1:]):
        dx, dy = x1 - x0, y1 - y0
        length = math.hypot(dx, dy)
        if length <= 0.0:
            continue
        yield (0.5 * (x0 + x1), 0.5 * (y0 + y1), length, math.atan2(dy, dx))


def build_urdf(course, thickness=0.001, visual=True, name="magnetic_course"):
    kinds = {t.get("kind", "track") for t in course.get("tapes", [])}
    for k in kinds:
        if k not in COLOR:
            raise ValueError(f"unknown tape kind {k!r} (track|marker)")
    lines = ['<?xml version="1.0"?>', f'<robot name="{name}">',
             '  <!-- generated by gen_tape_urdf.py: magnetic tape course for MagneticGuideSensor -->']
    for k in ("track", "marker"):
        lines.append(f'  <collision_material name="{k}"><magnetic_tape polarity="{k}"/></collision_material>')
    lines += ['  <link name="world"/>', '  <link name="tape_link">']
    n = 0
    for tape in course.get("tapes", []):
        kind = tape.get("kind", "track")
        width = float(tape.get("width", 0.025))
        pts = [(float(p[0]), float(p[1])) for p in tape["points"]]
        for (cx, cy, length, yaw) in segments(pts):
            # overlap the joints slightly so a sample point never falls in a crack
            geom = (f'<geometry><box size="{length + width * 0.5:.4f} {width:.4f} {thickness:.4f}"/></geometry>')
            origin = f'<origin xyz="{cx:.4f} {cy:.4f} {thickness / 2:.4f}" rpy="0 0 {yaw:.6f}"/>'
            if visual:
                lines.append(f'    <visual>{origin}{geom}<material name="tape_{kind}">'
                             f'<color rgba="{COLOR[kind]}"/></material></visual>')
            lines.append(f'    <collision>{origin}{geom}<collision_material name="{kind}"/></collision>')
            n += 1
    lines += ['  </link>',
              '  <joint name="tape_fix" type="fixed"><parent link="world"/><child link="tape_link"/></joint>',
              '</robot>', '']
    return "\n".join(lines), n


def self_test():
    course = {"tapes": [
        {"kind": "track", "width": 0.025, "points": [[0, 0], [2, 0], [2, 1]]},
        {"kind": "marker", "width": 0.025, "points": [[1.0, 0.035], [1.3, 0.035]]},
    ]}
    urdf, n = build_urdf(course)
    assert n == 3, n
    root = ET.fromstring(urdf)
    mats = {m.get("name"): m.find("magnetic_tape").get("polarity") for m in root.findall("collision_material")}
    assert mats == {"track": "track", "marker": "marker"}, mats
    link = root.find("link[@name='tape_link']")
    cols = link.findall("collision")
    assert len(cols) == 3 and len(link.findall("visual")) == 3
    assert [c.find("collision_material").get("name") for c in cols] == ["track", "track", "marker"]
    # second segment is vertical: yaw = pi/2, centre (2, 0.5)
    o = cols[1].find("origin")
    assert o.get("xyz").startswith("2.0000 0.5000"), o.get("xyz")
    assert abs(float(o.get("rpy").split()[2]) - math.pi / 2) < 1e-6
    assert root.find("joint").find("parent").get("link") == "world"
    print(f"self-test OK: {n} segments")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("course_json", nargs="?")
    ap.add_argument("out_urdf", nargs="?")
    ap.add_argument("--thickness", type=float, default=0.001)
    ap.add_argument("--no-visual", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()
    if args.self_test:
        self_test()
        return 0
    if not args.course_json or not args.out_urdf:
        ap.error("course_json and out_urdf are required (or --self-test)")
    with open(args.course_json) as f:
        course = json.load(f)
    urdf, n = build_urdf(course, thickness=args.thickness, visual=not args.no_visual)
    os.makedirs(os.path.dirname(os.path.abspath(args.out_urdf)), exist_ok=True)
    with open(args.out_urdf, "w") as f:
        f.write(urdf)
    print(f"{args.out_urdf}: {n} tape segments")
    return 0


if __name__ == "__main__":
    sys.exit(main())
